### ISSUE TITLE
Node crashes after several hours in the `urts.rs` module of the `bee-tangle` crate

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/bee#1191]
## Bug description

Bee crashes after running for >15 hours due to an invalid `unwrap` in `urts` module of the `bee-tangle` crate.

NOTE: I changed the bug description after some discussion below, because the suspected low disk space cannot be to blame here.

## Rust version

rustc 1.59.0 (9d1b2106e 2022-02-23)

## Bee version

0.3.0-rc4

## Hardware specification

Ubuntu 2-core VPS 

## Steps To reproduce the bug

1. Set pruning delay to `200`.
2. Run the node and wait.

## Expected behaviour

The node should run like a Duracell Bunny :battery: :rabbit:

## Actual behaviour

Well....it doesn't.

## Errors

Here are the last lines of the log printed to `stdout`:
```
2022-03-01 10:45:53 (UTC) bee_protocol::workers::index_updater       DEBUG Set milestone index 2643757 to 136 messages.
2022-03-01 10:45:53 (UTC) bee_ledger::workers::consensus::worker     INFO  Confirmed milestone 2643757: referenced 137, no transaction 137, conflicting 0, included 0, consumed 0, created 0, receipt false.
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::prune        DEBUG Pruning milestone 2643557...
2022-03-01 10:45:53 (UTC) bee_protocol::workers::index_updater       DEBUG Updated xMRSI values for 216 messages.
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /root/bee/bee-tangle/src/urts.rs:153:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by thibault-martinez** [comment]
What makes you think this is because the disk is full ? I think we would have a warning from the storage...
Here it looks like we are assuming the presence of metadata that is actually not there, I would say this is another case of the exact same situation we're having with the flags.

**Comment by Alex6323** [comment]
hmm, disk full *and* that bug happening at the same time? Possible, but I found it to be very unlikely. Doesn't mean you're wrong, though. What would be the warning the storage puts out, and when does it do that?

**Comment by thibault-martinez** [comment]
I don't know the exact warning but it would be at insertion, not at fetching like here.

**Comment by Alex6323** [comment]
alright...my reasoning was that it simply wasn't written to the storage, and when read - the data simply wasn't there. But that explanation doesn't make a lot of sense now that I think more about it, since at the time that is relevent for tip selection everything is still in memory (so it's not a matter of disk storage).

**Comment by Alex6323** [comment]
But tbh I haven't encountered such a plain panic in the `urts` module in a long time, so when I saw that the disk was full I found it more likely that this must be the underlying cause.

**Comment by Alex6323** [comment]
the `trace.log` ended with:
```
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 2421911312a1b542c1f9d47ce756656293f63f59244729b8afe07420484e28be until 2643559
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: a5b4f4bd5b833e8c8b6ce3ac8b5ab7fd6de3b62184c503c6d8132d5b8e13fdea until 2643558
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: a35767e48aaab7c625ed46be8beb4eda49b4996610d2990f90e5bb46acd2d58e until 2643559
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: c2711cfb2596381d8c05f5f74625a98b6f635f05e9ce62ce1c5faba05657c9f5 until 2643559
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: e415694244971ddeea5ae94878c517fadd4c3ae4ca2946c73907b2661e8b92a1 until 2643559
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: e4f44e796245fe34662061f3f666e81ad4a899aa100be34d07d5f00019f87a54 until 2643559
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 06879f0bd9b01d1fade586e65bd258fd6c08a7ea997b92821f2b53d49450c954 until 2643559
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 4a4a01a0c0d60ef7009e2795062815840b83877438534c0f61be3c1c0fddd165 until 2643558
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 69db4a98ac04ee5bcd05f1e501d9d60a0ff2c792595fc709d088b3f76ab58d95 until 2643558
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 8d569469dfb628bada3ae03a65556afea33f3c7498193abc2c565f03263f233f until 2643558
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 1e0a4b248609dad5d2046d094ce5b20ce643a14ac8afc649adf5d03c31b63361 until 2643558
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 83c185f5de96ec1b8903b52b533ea03e834659cbf901943e91e80a37df9ad5ae until 2643558
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 3ef3ea844e0292dd8518638744f3be87df8d74292ff3db4ef12427a0e8aa2dcd until 2643558
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 874568b046a5a7634d9ed555a298c747514098bd7b1779f62350654710ebbdb8 until 2643558
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: acee1c3c74adea7c9afb56e9e897ab8c34aa9b04aec38dddc0f44813f3b7330d until 2643558
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: baf409656562e164148aa510b255f171a470c5a20fbc9a46c5790d1ba5c91411 until 2643558
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 407b66f80f77a40c5ddcfe8eff70f488a704e3bc0d704e1da4ad61b4464a7299 until 2643558
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 4d1216e729d98186c1307c1a9cb08d4ae169970224cc30f91cfd8f7d36acd633 until 2643558
2022-03-01 10:45:53 (UTC) bee_protocol::workers::index_updater       DEBUG Updated xMRSI values for 216 messages.
2022-03-01 10:45:53 (UTC) bee_ledger::workers::pruning::batch        TRACE New SEP: 7faa34bb5414f5cd49484c9d1182a270b20ad077b8f313b90592a2ea6a483cc5 until 2643558
```

**Comment by Alex6323** [comment]
See those `await` points?
```rust
let omrsi = *tangle.omrsi(message_id).await.unwrap().index();
let ymrsi = *tangle.ymrsi(message_id).await.unwrap().index();
```
So what would happen here if one of those would be aborted due to a disk write task panicking?

**Comment by thibault-martinez** [comment]
I'm not sure to follow, if a write panics everything stops, so nothing happens to these await at all.

**Comment by Alex6323** [comment]
You're right. I was just trying to find a way to make a full disk responsible for what I was seeing. That would have meant something wrong with async/await in Rust which wasn't very likely in the first place, but bugs in Rust still happen quite regularly (I've encountered a number of compiler bugs already, so something wrong in Rust cannot simply be ruled out IMO). But in this case my speculation was wrong. I've had the panic again, and this time, the disk wasn't full.

**Comment by Alex6323** [comment]
```
2022-03-01 20:10:13 (UTC) bee_protocol::workers::solidifier          DEBUG Light solidification of milestone 2647143 019b2c30f13c19fa3494a46f5853ca0ee585a3bb897f1310db6bcb1593c9cf79 in [2647143;2647143].
2022-03-01 20:10:13 (UTC) bee_protocol::workers::solidifier          DEBUG Heavy solidification of milestone 2647143 019b2c30f13c19fa3494a46f5853ca0ee585a3bb897f1310db6bcb1593c9cf79: 0 messages requested in [2647143;2647143].
2022-03-01 20:10:13 (UTC) bee_protocol::workers::solidifier          DEBUG Light solidification of milestone 2647143 019b2c30f13c19fa3494a46f5853ca0ee585a3bb897f1310db6bcb1593c9cf79 in [2647143;2647143].
2022-03-01 20:10:13 (UTC) bee_protocol::workers::solidifier          DEBUG New solid milestone 2647143.
2022-03-01 20:10:13 (UTC) bee_protocol::workers::index_updater       DEBUG Set milestone index 2647143 to 144 messages.
2022-03-01 20:10:14 (UTC) bee_ledger::workers::consensus::worker     INFO  Confirmed milestone 2647143: referenced 145, no transaction 142, conflicting 0, included 3, consumed 3, created 4, receipt false.
2022-03-01 20:10:14 (UTC) bee_ledger::workers::pruning::prune        DEBUG Pruning milestone 2646943...
2022-03-01 20:10:14 (UTC) bee_protocol::workers::index_updater       DEBUG Updated xMRSI values for 217 messages.
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /root/bee/bee-tangle/src/urts.rs:153:57
```

**Comment by Alex6323** [comment]
I am changing the bug description.

**Comment by thibault-martinez** [comment]
Can you rebase to include https://github.com/iotaledger/bee/pull/1187 ?
I'm pretty sure this would fix it.

**Comment by Alex6323** [comment]
Alright :+1:
